name: 'GitHub Actions CloudFlare2DNSPod Bot'

on:
  push:
    branches: 
      - master
  repository_dispatch:
    types: cf
  schedule:
    - cron: '1-59/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'run cf2dns'
        env:
          KEY: ${{ secrets.KEY }}
          DOMAINS: ${{ secrets.DOMAINS }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
        run: python cf2dns_actions.py
      #清除过期记录
      - name: 'Delete older workflow runs and artifacts'
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 20
